# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
 name: overprovisioning
value: -1
globalDefault: false
description: "Priority class for overprovisioning pods."
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: overprovisioning-placeholder
 namespace: testing
spec:
 replicas: 5
 selector:
   matchLabels:
     app: overprovisioning-placeholder
 template:
   metadata:
     labels:
       app: overprovisioning-placeholder
   spec:
     priorityClassName: overprovisioning
     containers:
     - name: pause
       image: k8s.gcr.io/pause:3.2
       resources:
         requests:
           cpu: 386m