# Create a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
      nodeName: <your node name>