# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    name: testing
---
# Create a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssdrequired
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssdrequired
  template:
    metadata:
      labels:
        app: ssdrequired
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
      tolerations:
      - key: "disktype"
        operator: "Equal"
        value: "SSD"
        effect: "NoExecute"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "disktype"
                operator: In
                values:
                - "SSD"
---
# Create a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpurequired
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpurequired
  template:
    metadata:
      labels:
        app: gpurequired
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
      tolerations:
      - key: "GPU"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "GPU"
                operator: In
                values:
                - "true"