# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    name: testing
---
# Create a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: testing
spec:
  # Create lots of replicas
  replicas: 4
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
# Create a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache2
  namespace: testing
spec:
  # Create lots of replicas
  replicas: 4
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec: 
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
