apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo
  namespace: testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50